### ISSUE TITLE
用户输入 N / 0，程序不会拒绝输入，直接程序报错

### ISSUE THREAD

**Issue by Lexyguo** [jinxiaohang/Operation#2]
Please enter the number of questions you want to do
5
1*3=8／0
Exception in thread "main" java.util.InputMismatchException
	at java.util.Scanner.throwFor(Scanner.java:864)
	at java.util.Scanner.next(Scanner.java:1485)
	at java.util.Scanner.nextInt(Scanner.java:2117)
	at java.util.Scanner.nextInt(Scanner.java:2076)
	at src.Main.mul(Main.java:140)
	at src.Main.main(Main.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1

**Comment by Lexyguo** [comment]
可以判错N/0，但无法判断拒绝输入
![4](https://cloud.githubusercontent.com/assets/25717145/23829978/15256e96-073a-11e7-95ed-c6299b870e46.jpeg)
我理解的拒绝输入应该可以提示用户错误输入，且让其重新输入一遍正确的格式，但错误输入格式不算入错误格式中
